[2023-11-27 14:44:25,402] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: final_project_data_covid_etl.create_fact_province_daily scheduled__2023-11-26T00:00:00+00:00 [queued]>
[2023-11-27 14:44:25,410] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: final_project_data_covid_etl.create_fact_province_daily scheduled__2023-11-26T00:00:00+00:00 [queued]>
[2023-11-27 14:44:25,410] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-27 14:44:25,411] {taskinstance.py:1357} INFO - Starting attempt 2 of 4
[2023-11-27 14:44:25,411] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-27 14:44:25,428] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_fact_province_daily> on 2023-11-26 00:00:00+00:00
[2023-11-27 14:44:25,434] {standard_task_runner.py:52} INFO - Started process 1434 to run task
[2023-11-27 14:44:25,436] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'final_project_data_covid_etl', 'create_fact_province_daily', 'scheduled__2023-11-26T00:00:00+00:00', '--job-id', '473', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpunx6wbmf', '--error-file', '/tmp/tmppnetupyp']
[2023-11-27 14:44:25,436] {standard_task_runner.py:80} INFO - Job 473: Subtask create_fact_province_daily
[2023-11-27 14:44:25,489] {task_command.py:369} INFO - Running <TaskInstance: final_project_data_covid_etl.create_fact_province_daily scheduled__2023-11-26T00:00:00+00:00 [running]> on host 9bd194bc0dbc
[2023-11-27 14:44:25,559] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ricky
AIRFLOW_CTX_DAG_ID=final_project_data_covid_etl
AIRFLOW_CTX_TASK_ID=create_fact_province_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-26T00:00:00+00:00
[2023-11-27 14:44:25,560] {python.py:173} INFO - Done. Returned value was: None
[2023-11-27 14:44:25,573] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=final_project_data_covid_etl, task_id=create_fact_province_daily, execution_date=20231126T000000, start_date=20231127T144425, end_date=20231127T144425
[2023-11-27 14:44:25,610] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-27 14:44:25,658] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
