[2023-11-26 15:39:40,381] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_district scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26 15:39:40,422] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_district scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26 15:39:40,422] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:40,422] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-11-26 15:39:40,422] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:40,466] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_district> on 2023-11-24 00:00:00+00:00
[2023-11-26 15:39:40,485] {standard_task_runner.py:52} INFO - Started process 2584 to run task
[2023-11-26 15:39:40,500] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_district', 'scheduled__2023-11-24T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmp7s_lsswx', '--error-file', '/tmp/tmpmk34z_2_']
[2023-11-26 15:39:40,501] {standard_task_runner.py:80} INFO - Job 70: Subtask create_dim_district
[2023-11-26 15:39:40,718] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_district scheduled__2023-11-24T00:00:00+00:00 [running]> on host f384f2afcc4f
[2023-11-26 15:39:40,907] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_district
AIRFLOW_CTX_EXECUTION_DATE=2023-11-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-24T00:00:00+00:00
[2023-11-26 15:39:40,908] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 15:39:40,943] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_dim_district, execution_date=20231124T000000, start_date=20231126T153940, end_date=20231126T153940
[2023-11-26 15:39:40,992] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 15:39:41,024] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 17:57:12,855] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: data_covid_etl.create_dim_district scheduled__2023-11-24T00:00:00+00:00 [queued]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'create_dim_province'}
[2023-11-26 17:57:12,861] {local_task_job.py:101} INFO - Task is not able to be run
[2023-11-26 18:05:38,463] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_district scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26 18:05:38,472] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_district scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26 18:05:38,472] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:05:38,472] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:05:38,472] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:05:38,485] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_district> on 2023-11-24 00:00:00+00:00
[2023-11-26 18:05:38,490] {standard_task_runner.py:52} INFO - Started process 1166 to run task
[2023-11-26 18:05:38,492] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_district', 'scheduled__2023-11-24T00:00:00+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpkvwt02m6', '--error-file', '/tmp/tmp98kjlw6q']
[2023-11-26 18:05:38,493] {standard_task_runner.py:80} INFO - Job 197: Subtask create_dim_district
[2023-11-26 18:05:38,540] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_district scheduled__2023-11-24T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:05:38,613] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_district
AIRFLOW_CTX_EXECUTION_DATE=2023-11-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-24T00:00:00+00:00
[2023-11-26 18:05:38,614] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:05:38,625] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_dim_district, execution_date=20231124T000000, start_date=20231126T180538, end_date=20231126T180538
[2023-11-26 18:05:38,664] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:05:38,708] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26 18:10:54,103] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_district scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26 18:10:54,112] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_district scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26 18:10:54,112] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:10:54,112] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:10:54,112] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:10:54,127] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_district> on 2023-11-24 00:00:00+00:00
[2023-11-26 18:10:54,131] {standard_task_runner.py:52} INFO - Started process 1411 to run task
[2023-11-26 18:10:54,134] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_district', 'scheduled__2023-11-24T00:00:00+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpwp9cvvrt', '--error-file', '/tmp/tmp5__ua_q_']
[2023-11-26 18:10:54,134] {standard_task_runner.py:80} INFO - Job 229: Subtask create_dim_district
[2023-11-26 18:10:54,178] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_district scheduled__2023-11-24T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:10:54,246] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_district
AIRFLOW_CTX_EXECUTION_DATE=2023-11-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-24T00:00:00+00:00
[2023-11-26 18:10:54,247] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:10:54,260] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_dim_district, execution_date=20231124T000000, start_date=20231126T181054, end_date=20231126T181054
[2023-11-26 18:10:54,306] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:10:54,364] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
