[2023-11-26 15:39:40,295] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_province_daily scheduled__2023-11-25T00:00:00+00:00 [queued]>
[2023-11-26 15:39:40,337] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_province_daily scheduled__2023-11-25T00:00:00+00:00 [queued]>
[2023-11-26 15:39:40,337] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:40,337] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-11-26 15:39:40,337] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:40,413] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_fact_province_daily> on 2023-11-25 00:00:00+00:00
[2023-11-26 15:39:40,421] {standard_task_runner.py:52} INFO - Started process 2583 to run task
[2023-11-26 15:39:40,452] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_fact_province_daily', 'scheduled__2023-11-25T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpfwimyi95', '--error-file', '/tmp/tmpa634sw5c']
[2023-11-26 15:39:40,453] {standard_task_runner.py:80} INFO - Job 65: Subtask create_fact_province_daily
[2023-11-26 15:39:40,580] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_fact_province_daily scheduled__2023-11-25T00:00:00+00:00 [running]> on host f384f2afcc4f
[2023-11-26 15:39:40,808] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_fact_province_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-25T00:00:00+00:00
[2023-11-26 15:39:40,808] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 15:39:40,866] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_fact_province_daily, execution_date=20231125T000000, start_date=20231126T153940, end_date=20231126T153940
[2023-11-26 15:39:40,906] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 15:39:40,956] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 17:57:14,540] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: data_covid_etl.create_fact_province_daily scheduled__2023-11-25T00:00:00+00:00 [queued]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'create_fact_district_daily'}
[2023-11-26 17:57:14,546] {local_task_job.py:101} INFO - Task is not able to be run
